version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    # volumes:
    #   - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  fastapi-app:
    build:
      context: .
    container_name: fastapi-app
    ports:
      - "13860:7860"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
